export const offlineContent = [
  "/manifest.webmanifest",
  "/favicon.png",
  "/apple-touch-icon.png",
  "/icons/otterpuck-192.png",
  "/icons/otterpuck-512.png",
  "/models/otter-paws.glb",
  "/models/characters/otter.glb",
  "/models/characters/beaver.glb",
  "/models/arenas/tropical.glb",
  "/models/arenas/city.glb",
  "/art/arenas/tropical-panorama-painted.png",
  "/art/arenas/city-panorama-painted.png",
  "/art/arenas/island-rock-painted.png",
  "/art/arenas/tropical-map.webp",
  "/art/arenas/city-map.webp",
  "/art/learn/dummy-toon-v1.png",
  "/art/learn/curl-toon-v1.png",
  "/art/learn/shot-toon-v1.png",
  "/audio/dive.wav",
  "/audio/surface.wav",
  "/audio/electric-stream.m4a",
] as const;
